### PR TITLE
Command Soon

### PR DESCRIPTION
**Pull request by morshey77**
If you have a time make this command and sytem API

### CODE REVIEW

**Comment by Zoumi-Dev** [comment]
> If you have a time make this command and sytem API

I am currently working on commands such as /enderchest, /top and others...

**Comment by Zoumi-Dev** [comment]
> If you have a time make this command and sytem API

What would be the function of the /rank?

**Comment by morshey77** [comment]
The goal would be to replace pure Chat and Pure Perm

**Comment by Zoumi-Dev** [comment]
> The goal would be to replace pure Chat and Pure Perm

I won't do that, because simply in the future I want to put a scoreboard that could display the rank by PureChat and others. I prefer them to use PureChat.

**Pull request closed without merging**
